donation/urls.py
from donation.views import donationplaces
from django.urls import path

from . import views

app_name = 'donation'

urlpatterns = [
    path('donation', views.donation, name='donation'),
    path('savecontributors', views.savecontributors),
    path('donationplaces', views.donationplaces)
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('kasusupdate', views.kasusupdate, name='kasusupdate')
]

hotline/urls.py
from django.urls import path

from . import views
app_name = 'hotline'

urlpatterns = [
    path('hotline', views.hotline, name='hotline')
]

sharing/urls.py
from django.urls import path
from . import views

app_name = 'sharing'

urlpatterns = [
    path('sharing', views.sharing_page, name='sharing'),
    path('sharing-result', views.sharing_result, name='sharing-result'),
]

signup/urls.py
from django.urls import path
from signup.views import sign_up

app_name = 'signup'

urlpatterns = [
    path('signup', sign_up.as_view(), name='signup'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('hotline.urls')),
    path('', include('donation.urls')),
    path('', include('sharing.urls')),
    path('accounts/', include('signup.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

donation/models.py
from django.db import models

# Create your models here.
class Contributors(models.Model) :
    nama = models.CharField(max_length=30)
    kota = models.CharField(max_length=15)

home/models.py
from django.db import models

# Create your models here.
class subscribe_models(models.Model):
    nama = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return '%s' % self.nama

class kasus_models(models.Model):
    total = models.IntegerField()
    dirawat = models.IntegerField()
    sembuh = models.IntegerField()
    meninggal = models.IntegerField()
    update = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%d' % self.total

hotline/models.py
from django.db import models

# Create your models here.
class rumahsakit (models.Model):
    nama = models.CharField(max_length=60)
    nomor = models.CharField(max_length=60)

sharing/models.py
from django.db import models

# Create your models here.

AGE_CHOICES = [
        ('<14','14 tahun atau kurang'),
        ('15-49','15 sampai 49 tahun'),
        ('50-64','50 sampai 64 tahun'),
        ('>65','65 tahun atau lebih'),
        ]

GENDER_CHOICES = [
        ('laki-laki','Laki-Laki'),
        ('perempuan','Perempuan')
        ]

class Pengalaman(models.Model) :
    age = models.CharField('Berapa umur Anda?', choices=AGE_CHOICES, max_length=200, null=True)
    gender = models.CharField('Apa jenis kelamin Anda?', choices=GENDER_CHOICES, max_length=200, null=True)
    pengalaman = models.TextField('Bagikan pengalaman Anda seputar COVID-19!',null=True)

signup/models.py
from django.db import models

# Create your models here.

donation/forms.py
from django import forms
from .models import Contributors
class forms_contributors(forms.ModelForm):
    class Meta:
        model = Contributors
        fields = ['nama', 'kota']
    nama = forms.CharField(label='Nama', max_length=15, widget=forms.TextInput(attrs={'placeholder':'Contoh: Anonymous', 'class':'form-control'}))
    kota = forms.CharField(label='Kota', max_length=15, widget=forms.TextInput(attrs={'placeholder':'Contoh: Depok', 'class':'form-control'}))

home/forms.py
from django import forms
from .models import subscribe_models, kasus_models

class form_subscribe(forms.ModelForm):
    class Meta:
        model = subscribe_models
        fields = '__all__'
    nama = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Input your name here'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Input your e-mail here'}))

class form_kasus(forms.ModelForm):
    class Meta:
        model = kasus_models
        fields = '__all__'
    

hotline/forms.py
from django import forms
from .models import rumahsakit

class forms_rumahsakit(forms.ModelForm):
    class Meta:
        model = rumahsakit
        fields = [
            'nama', 'nomor'
        ]

sharing/forms.py
from django import forms
from .models import Pengalaman
from django.contrib.admin import models
from .models import AGE_CHOICES, GENDER_CHOICES


class SharingForm(forms.ModelForm):

    class Meta:
        model = Pengalaman
        fields = '__all__'
        
    widgets = {
         'age':forms.Select(choices=AGE_CHOICES, attrs={'class':'form-control'}),
         'gender':forms.Select(choices=GENDER_CHOICES, attrs={'class':'form-control'}),
         'pengalaman':forms.Textarea(attrs={'class':'form-control'})
    }

donation/views.py
from django.shortcuts import render, redirect
from .models import Contributors
from .forms import forms_contributors

# Create your views here.
def donation(request):
    contributors = Contributors.objects.all()
    total = Contributors.objects.all().count()
    response = {'form':forms_contributors, 'contributors':contributors, 'total':total}
    return render(request, 'donation.html', response)

def savecontributors(request):
    form = forms_contributors(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('/donationplaces')
    else:
        return redirect('/donation')

def donationplaces(request):
    return render(request, 'donationplaces.html')

home/views.py
from django.shortcuts import render, redirect
from .models import subscribe_models, kasus_models
from .forms import form_subscribe, form_kasus
from django.contrib import messages

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = form_subscribe(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Thankyou for subscribe us!")

    form = form_subscribe()
    subs = subscribe_models.objects.all()
    formkasus = form_kasus()
    kasus = kasus_models.objects.all()
    context = {
        'subs': subs,
        'form' : form,
        'kasus': kasus,
        'formkasus' : formkasus,
    }
    return render(request, 'index.html' , context)

def kasusupdate(request):
    if request.method == 'POST':
        formkasus = form_kasus(request.POST)
        if formkasus.is_valid():
            formkasus.save()
            messages.success(request, "Update successfully.")

    formkasus = form_kasus()
    kasus = kasus_models.objects.all()
    context = {
        'kasus': kasus,
        'formkasus' : formkasus,
    }
    return render(request, 'kasus.html' , context)

hotline/views.py
from django.shortcuts import render
from .forms import forms_rumahsakit
from .models import rumahsakit

# Create your views here.
def hotline(request):
    if request.method == 'POST':
        form = forms_rumahsakit(request.POST)
        if form.is_valid():
            form.save()

    form = forms_rumahsakit()
    rumah_sakit = rumahsakit.objects.all()
    context = {
        'rumah_sakit':rumah_sakit,
        'form' : form,
    }
    return render(request, 'HotlinePage.html' , context)

sharing/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Pengalaman
from .forms import SharingForm
from django.core import serializers

# Create your views here.

def sharing_page(request):
    sharing = Pengalaman.objects.all()
    form = SharingForm()
    if request.method == 'POST':  
        forminput = SharingForm(request.POST)
        if forminput.is_valid():
            forminput.save()
            return redirect('/sharing-result')
        else:
            return render(request, 'sharing-form.html', {'form':form, 'status': 'failed', 'data' : sharing})       
    else:
        current_data = Pengalaman.objects.all()
        return render(request, 'sharing-form.html', {'form':form, 'data':current_data})

def sharing_result(request):
    sharing = Pengalaman.objects.all()
    qs_json = serializers.serialize('json', sharing)
    return render(request, 'sharing-data.html',{'data':sharing, "chartData":qs_json} )

signup/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.

class sign_up(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/sign-up.html'

donation/templates/donation.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Donation</title>
{% endblock meta %}

{% block content %}
<div>
  {% include 'navbar.html' %}
</div>
<div id="carouselDonations" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselDonations" data-slide-to="0" class="active"></li>
    <li data-target="#carouselDonations" data-slide-to="1"></li>
    <li data-target="#carouselDonations" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static '1.png' %}" alt="Donate">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static '2.png' %}" alt="MariBerdonasi">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static '3.png' %}" alt="MariBerdonasi">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselDonations" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselDonations" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<h1 id="donate">Donate</h1>
<p id="donateText">Ayo bantu teman-teman kita yang kesulitan ditengah pandemi! <br>
(Hasil pengisian form akan ditampilkan pada tabel di bawah) <br></p>
<div class="donation" style="align-items: center;">
    <form method="POST" action="savecontributors">
        {% csrf_token %}
        <table>  
            <td>{{ form }}</td>  
            <td><input class="btn btn-info" type="submit" value="Next"></td>
        </table>
    </form>
</div>
<br>
<p id="donateText"><a href="donationplaces" style="color: #00A9A5; font-weight: bold;"> Click here!</a> jika ingin langsung menuju halaman tempat donasi.</p>
<br> <br>
<div class="row" style="background-color: #0b5350e8;">
  <div class="col">
  <h2 id="contributors" style="color: white;">Contributors</h2>
  <p style="text-align: center; font-weight: bold; color: rgb(240, 240, 240);">Total: {{ total }}</p>
  
    <div class="scrollable" style="">
    <table class="table table-bordered table-hover" style="">
      <thead class="thead-light">
        <tr>
          <th scope="col">Num</th>
          <th scope="col">Name</th>
          <th scope="col">City</th>
        </tr>
      </thead>
      <tbody>
        {% if contributors %}
          {% for contributor in contributors %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ contributor.nama }}</td>
            <td>{{ contributor.kota }}</td>
          </tr>
          {% endfor %}
        {% endif %}
      </tbody>
    </table>
    </div>
    <br><br>
  </div>
</div>


{% endblock content %}

donation/templates/donationplaces.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Donation</title>
{% endblock meta %}

{% block content %}
<div>
  {% include 'navbar.html' %}
</div>
<h1 id="donate">Donate</h1>
<p id="donateText">Pilih tempat untuk berdonasi</p>
<div class="rowplaces">
  <div class="row">
    <div class="col-md-6">
      <div class="card card-donate">
        <img src="https://imgix.kitabisa.com/85c80718-ebb1-486d-93a3-dd715eb069ca.jpg?ar=16:9&w=664&auto=format,compress" class="card-img-top" alt="donasi2">
        <div class="card-body">
          <a href="https://kitabisa.com/campaign/indonesialawancorona" target="_blank" rel="noopener noreferrer" class="btn btn-outline-info">Donate</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card card-donate">
        <img src="https://imgix.kitabisa.com/e08ba9de-78ca-4d11-af23-eb189ad647a9.jpg?ar=16:9&w=664&auto=format,compress" class="card-img-top" alt="donasi1">
        <div class="card-body">
          <a href="https://kitabisa.com/campaign/bisazakatmakanan" target="_blank" rel="noopener noreferrer" class="btn btn-outline-info">Donate</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card card-donate">
        <img src="https://imgix.kitabisa.com/4daa5abb-0f1e-40a7-8768-19da9c396961.jpg?ar=16:9&w=664&auto=format,compress" class="card-img-top" alt="donasisatwa">
        <div class="card-body">
          <a href="https://kitabisa.com/campaign/bantusatwamakan" target="_blank" rel="noopener noreferrer" class="btn btn-outline-info">Donate</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card card-donate">
        <img src="https://imgix.kitabisa.com/3ed4bab5-1341-436c-9130-2f172e901081.jpg?ar=16:9&w=664&auto=format,compress" class="card-img-top" alt="donasisembako">
        <div class="card-body">
          <a href="https://kitabisa.com/campaign/sembakountukrakyat" target="_blank" rel="noopener noreferrer" class="btn btn-outline-info">Donate</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="thankyou">
  <h2 id="contributors">Thank You For Your Contribution!</h2>
  <p id="donateText">Sumbanganmu sangat berarti bagi teman-teman di luar sana. <br>
    Terima kasih. Jangan lelah untuk berbagi!</p>
  <a type="button" id="btn-submit" class="btn btn-info" href="donation">Selesai Berdonasi</a>
</div>

{% endblock content %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<title>COVCARE</title>
{% endblock meta %}

{% block content %}
<div id="id-jumbotron">
    <div class="jumbotron text-right">
        {% include 'navbar.html' %}
        <div class="intro">
            <h1>Pandemi COVID-19</h1>
            <p>Mari tingkatkan rasa kepeduliaan kita terhadap 
                <br>satu sama lain demi melawan COVID-19 
                <br>melalui platform COVCARE.</p>
            <a class= "btn btn-info" href="/#id-subs"><span style="font-weight: bold;">Subscription</span></a>
        </div>
    </div>
</div>
<div id="id-info">
    <div class="informasi">
        <h1>Informasi COVID-19</h1>
        <p>COVID-19 dapat tersebar melalui droplet yang dikeluarkan ketika orang terinfeksi batuk, bersin, atau menghembuskan nafas.
            Droplet ini cepat jatuh dan bertahan selama 28 hari di permukaan benda.
            Lakukan langkah berikut untuk mencegah penyebarannya.
        </p>
    </div>
    <div class="row">
        <div class="col">
            <div class="card img-card" style="width: 13rem; border-radius: 30px;">
                <div class="card-body">
                    <img src='{% static "masker.svg" %}' style="height: 70px;" class="card-img-top">
                    <p class="card- text-center pt-3">
                        Pakai Masker
                    </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card img-card" style="width: 13rem; border-radius: 30px;">
                <div class="card-body">
                    <img src='{% static "cuci_tangan.svg" %}' style="height: 70px;" class="card-img-top">
                    <p class="card- text-center pt-3">
                        Cuci Tangan
                    </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card img-card" style="width: 13rem; border-radius: 30px;">
                <div class="card-body">
                    <img src='{% static "berjarak.svg" %}' style="height: 70px;" class="card-img-top">
                    <p class="card- text-center pt-3">
                        Jaga Jarak
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<section id="id-kasus">
    <h1 id="total-text">Kasus COVID-19 di Indonesia</h1>
    {% for i in kasus %}
    {% if forloop.last %}
    <div class="row" style="justify-content: center;">
        <div class="card text-white bg-info mb-3" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Terkonfirmasi</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.total }}</h5>
            </div>
        </div>
        <div class="card text-white bg-danger mb-3" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Dirawat</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.dirawat }}</h5>
            </div>
        </div>
        <div class="card text-white bg-success mb-3" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Sembuh</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.sembuh }}</h5>
            </div>
        </div>
        <div class="card text-white bg-dark mb-3" style="max-width: 10rem;">
            <div class="card-header">
                <h6>Meninggal</h6>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ i.meninggal }}</h5>
            </div>
        </div>
    </div>
    <div class="row" style="justify-content: center;">
        <p style="color: black;">Terakhir update: {{ i.update }}</p>
    </div>
    {% endif %}
    {% endfor %}
    <div class="btnupdate" style="text-align: center; padding-top: 10px;">
        <a class="btn btn-outline-info" href="{% url 'home:kasusupdate' %}">Klik untuk melakukan update kasus</a>
    </div>
</div>
<div id="id-gejala">
    <div class="row" style="margin-bottom: 50px;">
        <div class="col d-flex justify-content-center">
            <div class="card" style="width: 60rem; border-radius: 30px; background-color: #eeeeee;">
                <div class="row">
                    <div class="col-sm-left">
                        <div class="text-title">
                            <p style="color: black; font-size: 40px; font-weight: bold;">Gejala</p>
                        </div>
                    </div>
                    <div class="col-sm-right" style="width:600px; padding: 30px;">
                        <div class="text-body">
                            <p style="color: black; font-size: 15px; text-align: left;">
                                Pada umumnya orang yang terpapar virus COVID-19 akan menunjukkan gejala pada hari
                                ke-5 hingga hari ke-14. Berikut gejala yang biasanya terjadi,
                                <br>Gejala Umum:
                            <br>1. Demam
                            <br>2. Batuk kering
                            <br>3. Merasa lelah
                            <br>
                            <br>Gejala Serius:
                            <br>1. Sesak nafas
                            <br>2. Nyeri pada dada
                            <br>3. Hilang kemampuan berbicara atau bergerak 
                            <br>
                            <br>Jika merasakan gejala diatas, segera kunjungi/hubungi rumah sakit rujukan dengan klik tombol dibawah ini.
                            <br>
                            <br>
                            <a class= "btn btn-info" href="{% url 'hotline:hotline' %}"><span style="font-weight: bold;">Hotline.</span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="id-penanganan">
    <div class="row" style="margin-bottom: 50px;">
        <div class="col d-flex justify-content-center">
            <div class="card" style="width: 60rem; border-radius: 30px; background-color: #eeeeee;">
                <div class="row">
                    <div class="col-sm-left">
                        <div class="text-title">
                            <p style="color: black; font-size: 40px; font-weight: bold;">Penanganan</p>
                        </div>
                    </div>
                    <div class="col-sm-right" style="width:600px; padding: 30px;">
                        <div class="text-body">
                            <p style="color: black; font-size: 15px; text-align: left;">
                                Jika Anda merasa sakit, lakukan beberapa penanganan mandiri sebagai berikut,
                                <br>1. Gunakan ruangan yang terpisah dari keluarga atau kerabat
                                <br>2. Lakukan disinfeksi pada permukaan yang sering disentuh
                                <br>3. Jaga pola hidup sehat
                                <br>4. Batasi kontak sosial dengan siapapun
                                <br>
                                <br>Untuk menjaga kesehatan psikis selama terinfeksi, ceritalah kepada orang yang Anda percaya atau Anda dapat berbagi cerita dengan klik tombol dibawah ini.
                                <br>
                                <br>
                                <a class= "btn btn-info" href="{% url 'sharing:sharing' %}"><span style="font-weight: bold;">Sharing.</span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section id="id-subs">
    <h2>SUBSCRIBE TO COVCARE</h2>
    <form method="POST" action="#id-subs">
        {% csrf_token %}
        <table>  
            <td>{{ form }}</td>
        </table>
        {% if messages %}
        <ul style="list-style-type:none">
            {% for message in messages %}
                <li class="text-success">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <input class="btn btn-info" type="submit" value="SUBSCRIBE" style="font-weight: bold;">
    </form>
</div>
{% endblock content %}

sharing/templates/sharing-data.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kumpulan Sharing</title>
{% endblock meta %}

{% block content %}
<div>
    {% include 'navbar.html' %}
</div>

<div class="d-flex flex-column justify-content-center align-items-center">
    <h1 id="sharing-header">Sharing</h1>
    <p class="sharing-desc">Kumpulan pengalaman masyarakat seputar COVID-19</p>
    <a href="{% url 'sharing:sharing' %}" id="btn-result" class="btn btn-outline-primary" role="button" aria-pressed="true">Bagikan Pengalaman</a>  
</div>

<div class="chart-container">
    <div id="agechart"></div>
    <div id="genderchart"></div>
</div>

<div class="d-flex flex-column justify-content-center" style="padding:2rem 8rem;">
    <p style="font-size:2rem;font-weight: bold;">Pengalaman</p>
    <hr/>
    {% for field in data %}
        <p>{{field.pengalaman}}</p>
        <hr/>
    {% endfor %}
</div>
{% endblock content %}

{% block script %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
// Load google charts
google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);

// Draw the chart and set the chart values
function drawChart() {

var datas = JSON.parse("{{chartData|escapejs}}"); 

var count14 = datas.filter((el)=>{
    return el.fields.age==="<14"
})
var count1549 = datas.filter((el)=>{
    return el.fields.age==="15-49"
})
var count5064 = datas.filter((el)=>{
    return el.fields.age==="50-64"
})
var count65 = datas.filter((el)=>{
    return el.fields.age===">65"
})

var dataAge = google.visualization.arrayToDataTable([
  ['Age', 'Count'],
  ['14 tahun atau kurang', count14.length],
  ['15 sampai 49 tahun', count1549.length],
  ['50 sampai 64 tahun', count5064.length],
  ['65 tahun atau lebih', count65.length]
]);
var countPerempuan = datas.filter((el)=>{
    return el.fields.gender==="perempuan"
})
var countLelaki = datas.filter((el)=>{
    return el.fields.gender==="laki-laki"
})

var dataGender = google.visualization.arrayToDataTable([
  ['Gender', 'Count'],
  ['Laki-Laki', countLelaki.length],
  ['Perempuan', countPerempuan.length],
]);

  // Optional; add a title and set the width and height of the chart
  var options = {
      'title':'Range Umur', 'width':500, 'height':400,
      colors: ['#3d819b','#205f6c', '#0c484d', '#00485d']
  };

  var options2 = {
      'title':'Jenis Kelamin', 'width':500, 'height':400,
      colors: ['#20474D', '#4E8098']
  };
  
  // Display the chart inside the <div> element with id="piechart"
  var chartAge = new google.visualization.PieChart(document.getElementById('agechart'));
  var chartGender = new google.visualization.PieChart(document.getElementById('genderchart'));
  chartAge.draw(dataAge, options);
  chartGender.draw(dataGender,options2);
}
</script>
{% endblock script %}

sharing/templates/sharing-form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sharing</title>
{% endblock meta %}

{% block content %}
<div>
  {% include 'navbar.html' %}
</div>
<style>
  textarea{
    padding:1rem;
  }
</style>
<div class="d-flex flex-column justify-content-center align-items-center">
  <h1 id="sharing-header">Sharing</h1>
    <p class="sharing-desc">Bagikan pengalaman Anda seputar COVID-19. <b>Pengalaman Anda akan ditampilkan pada halaman 
      <a href="{% url 'sharing:sharing-result' %}">Kumpulan Sharing</a>.</b> </p>
    <p class="sharing-desc">Sharing bersifat anonim.</p>
  
  <a href="{% url 'sharing:sharing-result' %}" id="btn-result" class="btn btn-outline-primary" role="button" aria-pressed="true">Lihat Kumpulan Sharing</a>  


</div>


  <form method="POST">
    {% csrf_token %}
    <div class="mr-auto ml-auto" style="width: 50%;">
        {% for field in form %}
        <div class="form-group" style="display: flex;flex-direction: column;">
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}
    <br>
    <div class="container">
        <input type="submit" value="Submit" id="btn-submit"class="btn btn-primary click">
    </div>
    </div>
    <br> <br>

</form>



{% endblock content %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: #092327;">
    <a class="navbar-brand" href="#">
        <div class ="title">
            covcare.
        </div>
    </a>
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'home:index' %}">
                    <div class ="navbar-item-text">
                        Home 
                    </div>
                    <span class="sr-only">
                        (current)
                    </span>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'sharing:sharing' %}">
                    <div class ="navbar-item-text">
                        Sharing
                    </div>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'donation:donation' %}">
                    <div class ="navbar-item-text">
                        Donation
                    </div>
                </a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'hotline:hotline' %}">
                    <div class ="navbar-item-text">
                        Hotline
                    </div>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'logout' %}">
                    <div class ="navbar-item-text">
                        Log Out
                    </div>
                </a>
            </li>
            {% else %}
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'login' %}">
                    <div class ="navbar-item-text">
                        Log In
                    </div>
                </a>
            </li>
            {% endif %}
            <li class="nav-item p-2">
                <a class="nav-link" href="{% url 'signup:signup' %}">
                    <div class ="navbar-item-text">
                        Sign Up
                    </div>
                </a>
            </li>
        </ul>
    </div>
</nav>